mcneel/compute.rhino3d

- EndPoint.cs
- EndPointDictionary.cs
- FixedEndpoints.cs
- Program.cs
- RhinoCommon.Rest.csproj
Adding explicit endpoints that map to a single function in RhinoCommon. We are still supporting the endpoint that performs a best guess at the overload to call.
> Add explicit endpoints

- .codedeploy/appspec.yml
- src/compute.frontend/NancyPipelineExtensions.cs
- src/compute.frontend/compute.frontend.csproj
- src/compute.frontend/packages.config
* Stop service during `BeforeInstall` instead of `ApplicationStop` because the latter doesn't run for the very first deployment and we might be deploying onto fresh instances launched by the ASG
* Use EC2 instance ID instead of hostname, if available
* Remove RhinoCommon dep from frontend since it's not necessary and was getting copylocal'd; `/version` now reports the proper Rhino WIP version number, not the copylocal'd RhinoCommon.dll version.
See COMPUTE-6
> Improvements to make compute play nicer with CodeDeploy

- src/compute.client/JavascriptClient.cs
- src/compute.client/Program.cs
A couple of quick fixes...
The former makes it possible to `compute = require('./compute.rhino3d.js')` in node.js – assuming compute.rhino3d.js is in the same directory as the calling code (or we could publish an npm package).
> Add module.exports line to make compute.rhino3d.js work with node.js and fix computegen console colour

- src/compute.geometry/DataCache.cs
- src/compute.geometry/GeometryEndPoint.cs
- src/compute.geometry/compute.geometry.csproj
Remote parameters
All parameters can now be passed as a dictionary of
{"url":"http address to data"}
Data will be fetched from the remote URL and cached on the local compute server in case it is requested again.
> Remote parameter support and parameter caching

- README.md
Added that also desktop Windows 10 Pro clients (can other OS be used as well?) and not only Server 2016 can run Compute on developer's local machines. 
This is an important additional statement since the original statement gives the impression that that only Server 2016 can be used, pushing away developers who don't have access to, or don't want to, install an additional server.
> Also Windows 10 Pro clients can run Rhino Compute.

- src/compute.frontend/NancyPipelineExtensions.cs
- src/compute.frontend/Proxy.cs
Removes the `/healthcheck` endpoint from the frontend so that it gets passed through the proxy to the backend. This way we'll know if the backend is down. Along the way I found that compute doesn't like it when the `Host` header from the original request is passed through to the backend in certain circumstances. The requests from AWS` health checker come back with 400 Bad Request (invalid hostname) errors. This also happens for any request when running compute in Docker.
TL;DR:
* `/healthcheck` now handled by the backend
* `Host` header from original request is no longer passed to the backend
> Proper /healthcheck (take 2)

- .gitignore
- Dockerfile
Thanks to @whitelioness for sharing an early version of this Dockerfile.
Uses windows:1809 base image. Switch to 1903 if running on latest
Windows 10 or Windows Server 1903. Requires "process" isolation.
Fixes COMPUTE-76
> Add dockerfile 🐳

- src/compute.frontend/Frontend.cs
- src/compute.frontend/NancyPipelineExtensions.cs
- src/compute.frontend/Proxy.cs
- src/compute.geometry/Program.cs
The `api_token` header wasn't allowed. While I was in there I fixed a bug where proxy (POST) errors looked like CORS issues.
> Allow alternative auth method to work with CORS

- src/compute.frontend/Proxy.cs
- src/compute.geometry/Bootstrapper.cs
- src/compute.geometry/Logging.cs
- src/compute.geometry/Program.cs
- src/compute.geometry/Startup.cs
- src/compute.geometry/compute.geometry.csproj
Adopting OWIN (or Katana, Microsoft's OWIN implementation) will enable us to build a web application that can run either as a console executable _or_ under IIS. So far I've done the first part by replacing Nancy.Hosting.Self with OWIN.
* Wraps Nancy with OWIN, self-host only for now
* Handles CORS in the OWIN middleware – far, _far_ more straightforward than trying to do this consistently in Nancy (successful requests, unhandled exceptions and 404s all follow slightly different paths in Nancy)
* Also uses OWIN to add simple request logging which will make developing applications on top of compute more transparent
* Adds the environment variable `COMPUTE_BIND_URLS` (name up for discussion) as a way to specify which protocols, interfaces and ports to listen on, e.g. …
> Replace Nancy self-host with OWIN

- Dockerfile
* Uses latest rhino wip release
* Updates licensing mechanism to use RHINO_TOKEN
* Adds solution for pre-installing .net 4.8 when using 1809 base image
* Mentions using yak to install plug-ins
> Update Dockerfile (licensing, .NET 4.8 and yak)

- appveyor.yml
- src/README.md
- src/compute.frontend/compute.frontend.csproj
- src/compute.geometry/compute.geometry.csproj
- src/compute.sln
The compute.frontend project is used solely on compute.rhino3d.com and causes confusion when getting compute set up.
The recommended way to use compute is to run compute.geometry and put something like the [AppServer](https://github.com/mcneel/compute.rhino3d.appserver) in front of it to control access and implement use-case specific behaviour like caching.
> Remove compute.frontend project from compute.sln

- src/compute.client/PythonClient.cs
- src/compute.client/RhinoComputeHeader.cs
- src/compute.geometry/RhinoCompute.cs
Allows the python and .net Compute clients to work with self-hosted Compute servers that have `RHINO_COMPUTE_KEY` configured
> Add api key option to python and .net client generators

- src/compute.geometry/Config.cs
- src/compute.geometry/GrasshopperDefinition.cs
- src/compute.geometry/Logging.cs
- src/compute.geometry/Program.cs
- src/compute.geometry/ResthopperEndpoints.cs
This is the result of some work to get Compute to play nicer with Ladybug Tools. It includes a different method of solving the Grasshopper definition and more logging to get insight into what might be going wrong with a definition that isn't behaving on Compute.
* Grasshopper definition solved in one go instead of as needed per output (#118)
* Logs errors from Grasshopper components' `RuntimeMessages` (#107)
* Returns HTTP 500 if there were any errors in the definition (doesn't affect the body)
* Control debug logging with `RHINO_COMPUTE_DEBUG=true` (default when running `Debug` configuration)
* Adds more debug logging...
* `Data` property of exceptions reported by RhinoCommon
* Warnings and remarks in `RuntimeMessages`
> Solve entire grasshopper definition at once and log errors better

- src/compute.geometry/GrasshopperDefinition.cs
Add definition to `DocumentServer` to raise `DocumentAdded` event. This event is used by some plug-ins as a way to register handlers for `GH_Document` events when the doc is loaded.
Primarily this is being added to support plug-ins which interact with `SolutionStart` and `SolutionEnd` to do multi-stage solves.
This overload of `AddDocument` is very basic and I haven't seen anything weird so far...!
> Fire document added event when setting up definition

- src/compute.client/PythonClient.cs
Changes the behaviour of `zip()` in Python 2 to use `izip()` and return an iterator as in Python 3. The iterator is then converted to a `list`.
Fixes COMPUTE-71
> Fix multiple in py3 client

- src/compute.geometry/GeometryEndPoint.cs
The python and javascript clients assume that RhinoCommon methods with no params have their own explicit endpoint, i.e. `/rhino/geometry/curve/duplicatesegments-curve` (#142).
I can't see any negative effects of adding a few more endpoints and this matches the pattern used for methods which have parameters.
```shell
/namespace/type/method
/namespace/type/method-type             # <-- NEW
/namespace/type/method-type_arg1_arg2
```
For reference, explicit endpoints were originally added in #3.
> Add explicit endpoints for overloads with no params

- appveyor.yml
- src/compute.components/Hops.csproj
- src/compute.components/Hops.sln
- src/compute.components/LocalServer.cs
- src/compute.geometry/Program.cs
- src/compute.geometry/compute.geometry.csproj
Part of #164
When path references a local file, try to launch a compute server on the same computer. For now, the compute server launches in a full console window so we can watch what is actually happening.
> Auto launch compute when needed by Hops

- src/compute.components/HopsComponent.cs
- src/compute.components/RemoteDefinition.cs
Part of issue #164 . This handles the case where a definition has gone missing on the computer where the user is working.
> Show error when definition file can't be found

- src/compute.geometry/GrasshopperDefinition.cs
It messes with hops' input param parsing and it isn't really necessary - we can infer from the presence of min/max values instead.
> Don't give sliders a custom name

- src/compute.rhino3d/ComputeChildren.cs
- src/compute.rhino3d/Program.cs
- src/compute.rhino3d/Proxy.cs
- src/compute.rhino3d/Startup.cs
- src/compute.rhino3d/compute.rhino3d.csproj
- src/compute.sln
First step for child process architecture #148 
Parent application is called compute.rhino3d.exe and is aa ASP.NET Core 5 application.
Not working yet, just getting the initial bare bones project committed.
Using Carter for now as it is very similar to NancyFX. Looks like it should be easy to remove this dependency in the future if we feel the need and as we learn more about writing ASP.NET Core
> Add basic skeleton for new parent compute.rhino3d.exe app

- src/compute.components/Servers.cs
> Bump wait time for compute.geometry to launch up to 60 seconds

- src/compute.components/HopsComponent.cs
- src/compute.components/Properties/AssemblyInfo.cs
- src/compute.geometry/GrasshopperDefinition.cs
also prefix hash with md5 so internal code doesn't accidentally think it is a GUID
> switch to new form of ShowModal for Mac

- src/compute.geometry/GrasshopperDefinition.cs
> Preserve paths when returning a tree

- src/hops/RemoteDefinition.cs
Let Grasshopper figure out the branch structure, instead of setting it explicitly
Fixes #275
> Set output as list if only one branch

- src/build_hops_dist.py
- src/compute.geometry/compute.geometry.csproj
- src/hops/Hops.csproj
- src/hops/manifest.yml
- src/rhino.compute/rhino.compute.csproj
* Updates hops csproj format to support new `dotnet` tooling
* Simplifies the publishing script, by using `dotnet publish` on hops.sln and adding `PublishDir` to each csproj
* Adds manifest.yml to source control
> Migrate hops.csproj to sdk-style and update dist script

- src/hops.sln
During he Hops.csproj build the `_CopyOutOfDateSourceItemsToOutputDirectory` target was copying rhino.compute.exe and rhino.compute.runtimeconfig.json to the output directory, next to Hops.gha. Removing the build dependency on rhino.compute.csproj fixes this. These files are included in the rhino.compute directory.
> Don't copy rhino.compute.exe to root of package

- Dockerfile
* Builds `rhino.compute` using .NET 5.0, but still only uses `compute.geometry`
* Updates Rhino to 7.4
> Update Dockerfile to work with new compute.sln

- src/hops/RemoteDefinition.cs
Reverts mcneel/compute.rhino3d#351
This breaks potential future caching with md5 hashes
> Revert "use path to definition when running local"

- src/hops/HopsAppSettingsUserControl.cs
- src/hops/Properties/AssemblyInfo.cs
- src/hops/RemoteDefinition.cs
Error messages were being thrown away. See
https://discourse.mcneel.com/t/hops-cannot-read-errors-after-0-6-0-update/125144
> Fix component from rebuilding on all exceptions thrown from server

- src/compute.geometry/ResthopperEndpoints.cs
- src/hops/Properties/AssemblyInfo.cs
this was causing deadlock with nested hops calls
> do not block the server when reading definition metadata

- CHANGELOG.HOPS.md
- src/compute.geometry/GrasshopperDefinition.cs
This will effect the behaviour of plug-ins that do not handle this event in a compute-friendly way (in hops/compute only), but at least it won't prevent it from running.
> Catch and log exceptions in DocumentAdded event handlers

- src/rhino.compute/Config.cs
- src/rhino.compute/ReverseProxy.cs
Adds the `RHINO_COMPUTE_TIMEOUT` environment variable for configuring the request timeout (in seconds) for the `HttpClient` used when reverse proxying requests to compute.geometry.
To test, configure the env var for the `rhino.compute` profile in launchSettings.json (see below) and try to solve [sleep.gh](https://github.com/mcneel/compute.rhino3d/files/8193121/sleep.zip) (sleeps for 10 seconds before returning).
```
"environmentVariables": {
"RHINO_COMPUTE_TIMEOUT": "2"
}
```
See https://discourse.mcneel.com/t/httpclient-timeout-of-100-seconds-with-rhino-compute/138952
> Make reverse proxy request timeout configurable

- src/hops/HopsComponent.cs
Html Help Source help url is not correct.
I changed it to the new url.
> Help URI incorrect
