mcneel/compute.rhino3d

- README.md
* Moved things around to prioritise "getting started" and "configuration" over "building from source"
* Arranged config section in a table to make it easier to read
> Major reorg of README

- src/compute.client/ClassBuilder.cs
- src/compute.client/ComputeClient.cs
- src/compute.client/DotNetClient.cs
- src/compute.client/JavascriptClient.cs
- src/compute.client/Program.cs
- src/compute.client/PythonClient.cs
- src/compute.client/README.md
- src/compute.client/computegen.csproj
- src/compute.geometry/FixedEndpoints.cs
- src/compute.geometry/Python.cs
- src/compute.geometry/RhinoCompute.cs
> Tune up RhinoCompute C# client and allow as downloaded attachment

- src/compute.geometry/RhinoCompute.cs
> Update RhinoCompute.cs to compile with current Rhino3dmIO

- src/compute.client/ClassBuilder.cs
- src/compute.client/python_client/compute_rhino3d/Curve.py
- src/compute.client/python_client/compute_rhino3d/Intersection.py
- src/compute.client/python_client/compute_rhino3d/Mesh.py
- src/compute.client/python_client/setup.py
> computegen missed functions when nested classes exist

- src/compute.client/ClassBuilder.cs
- src/compute.client/ComputeClient.cs
- src/compute.client/DotNetClient.cs
- src/compute.geometry/Program.cs
- src/compute.geometry/RhinoCompute.cs
Also update RhinoCompute.cs to support functions with more than one output parameter
> Early python test

- src/compute.geometry/Program.cs
> Add headless warmup code for GH

- .gitignore
- src/compute.client/ComputeClient.cs
- src/compute.client/python_client/compute_rhino3d/Brep.py
- src/compute.client/python_client/compute_rhino3d/Curve.py
- src/compute.client/python_client/compute_rhino3d/Intersection.py
- src/compute.client/python_client/compute_rhino3d/Mesh.py
- src/compute.client/python_client/compute_rhino3d/Surface.py
- src/compute.client/python_client/compute_rhino3d/Util.py
- src/compute.client/python_client/setup.py
> Add version user-agent to client libs

- src/compute.client/ClassBuilder.cs
- src/compute.client/ComputeClient.cs
- src/compute.client/Program.cs
- src/compute.client/PythonClient.cs
- src/compute.client/RstClient.cs
- src/compute.client/computegen.csproj
- src/compute.client/python_client/compute_rhino3d/Brep.py
- src/compute.client/python_client/compute_rhino3d/Curve.py
- src/compute.client/python_client/compute_rhino3d/Mesh.py
- src/compute.client/python_client/setup.py
Cite COMPUTE-49
Autogenerate rst files for python that can be run through sphinx to generate docs
> Autogenerate rst files for python docs

- src/compute.geometry/GeometryEndPoint.cs
- src/compute.geometry/Program.cs
- src/compute.geometry/compute.geometry.csproj
- src/compute.geometry/packages.config
> Add python endpoint

- src/compute.geometry/RhinoCompute.cs
> Add user agent info to .NET client

- src/compute.frontend/NancyPipelineExtensions.cs
> Attempt to get client ip behind lb

- src/compute.geometry/Program.cs
- src/compute.geometry/compute.geometry.csproj
- src/compute.geometry/packages.config
> Update Python Evaluate to use list of variable names to return

- src/compute.client/ComputeClient.cs
- src/compute.client/JavascriptClient.cs
* Published to npm as v0.5.2
* package.json and README.md moved to mcneel/computeclient_js
> Update js client support for node

- .codedeploy/appspec.yml
- .codedeploy/scripts/chown.bat
> Update CodeDeploy config to allow service to be run as "compute" user

- appveyor.yml
- src/compute.geometry/FixedEndpoints.cs
> Add git sha to /version info

- src/compute.geometry/GeometryEndPoint.cs
- src/compute.geometry/Program.cs
Moved python evaluation routine to the python plug-in and used HostUtils.RegisterComputeEndPoint from the plugin to provide a custom endpoint.
> Add support for defining custom endpoints

- src/compute.geometry/ResthopperEndpoints.cs
Clears up a memory leak in the resthopper end point
> Dispose the GH document at the end of a resthopper call

- src/compute.client/JavascriptClient.cs
* Adds a `DataTree` class and an `evaluateDefinition()` convenience method
* Leaves the implementer to read the file and accepts a string or byte array (Uint8Array)
* strips bom before base64 encoding .ghx file read by node.js (see #62)
> Add grasshopper to js client

- appveyor.yml
- docs/installation.md
Trying to improve clarity and get the more important information higher up in the docs
> Remove src/bin/Release from .zip and another round of improvements to the "getting started" doc

- Dockerfile
Thanks to @karimi for the suggestion
> Update docker build to use msbuild /restore

- src/compute.geometry/ResthopperEndpoints.cs
> Use FromJson to deserialize curves

- src/compute.client/ComputeClient.cs
- src/compute.client/JavascriptClient.cs
- src/compute.client/Program.cs
- src/compute.client/PythonClient.cs
- src/compute.client/RstClient.cs
- src/compute.geometry/Endpoints/GrasshopperEndpoint.cs
> update javascript and python clients for Resthopper calls

- src/compute.client/DotNetClient.cs
- src/compute.geometry/ResthopperEndpoints.cs
- src/compute.geometry/RhinoCompute.cs
> update client for resthopper support

- src/compute.geometry/IO/Schema.cs
- src/compute.geometry/ResthopperEndpoints.cs
This would allow for getting more information about the params without changing the existing API
> handling query params in /io

- src/compute.geometry/IO/Schema.cs
- src/compute.geometry/ResthopperEndpoints.cs
This is similar to https://github.com/mcneel/compute.rhino3d/pull/91, just cleaned up to not clutter the endpoint with query parameters, and the schema with a new class.
> Cleaning up io endpoint and return data

- src/compute.frontend/NancyPipelineExtensions.cs
Prevents exceptions from being masked by CORS errors
> Add CORS headers to 500 responses

- src/compute.frontend/Logging.cs
- src/compute.frontend/NancyPipelineExtensions.cs
- src/compute.geometry/Logging.cs
> A couple of minor tweaks to make compute's logging play nicer with docker

- script/Update-RhinoWIP.ps1
- script/update-rhino.ps1
Add a Powershell script to update Rhino WIP. 
Useful as a scheduled task before the current version expires.
> Add PS script to update Rhino WIP

- src/compute.geometry/GeometryEndPoint.cs
I think this makes sense based on the if/else behaviour on lines 511-514
> Only add as many out params as we need

- src/compute.frontend/Authentication/ApiKey.cs
- src/compute.frontend/Authentication/RhinoAccounts.cs
- src/compute.frontend/NancyPipelineExtensions.cs
- src/compute.frontend/Program.cs
- src/compute.frontend/Proxy.cs
- src/compute.frontend/RequestStashing.cs
- src/compute.frontend/compute.frontend.csproj
- src/compute.frontend/compute.frontend.sln
A few updates to the frontend project that we use for compute.rhino3d.com. Probably not much use to anyone else!
* Reuses `HttpClient` instead of creating a new one for every request
* Limits requests to 100/min per IP address
* Proxies `Content-Type` header to backend
* Adds /robots.txt
> Update the frontend!

- src/compute.client/PythonClient.cs
Generates the code in mcneel/computeclient_py#11
> Generate python code to decode BoundingBox

- src/compute.geometry/Bootstrapper.cs
> Ignore a few more assemblies during autoregistration

- src/compute.components/LocalServer.cs
- src/compute.components/RemoteDefinition.cs
- src/compute.components/RemoteSolveComponent.cs
> Make Hops component task capable

- src/compute.components/RemoteDefinition.cs
- src/compute.components/RemoteSolveComponent.cs
- src/compute.geometry/DataCache.cs
- src/compute.geometry/IO/Schema.cs
- src/compute.geometry/ResthopperEndpoints.cs
> Add cache on server option

- src/compute.components/HopsComponent.cs
- src/compute.components/LocalServer.cs
Play with launching multiple compute instances from Hops via context menu
> improve logic in Hops for launching multiple compute instances

- docs/deploy.md
- docs/develop.md
- src/README.md
We don't need to add a full readme.md for hops yet. Just adding this to the src directory readme seems good enough for now.
Closes #169
> Update src readme to include hops

- src/compute.components/RemoteDefinition.cs
- src/tests/hops_python.py
> Add python script test that can be called from Hops

- src/compute.components/LocalServer.cs
- src/compute.components/RemoteDefinition.cs
- src/compute.geometry/GrasshopperDefinition.cs
> solve definition based on single component guid

- src/compute.components/HopsComponent.cs
> Handle web exception when reading a component

- src/compute.components/HopsComponent.cs
- src/compute.components/RemoteDefinition.cs
- src/compute.geometry/GrasshopperDefinition.cs
- src/compute.geometry/IO/Schema.cs
> support defaults on inputs for built-in components

- src/compute.geometry/DataCache.cs
- src/compute.geometry/GrasshopperDefinition.cs
- src/compute.geometry/ResthopperEndpoints.cs
> add file watcher to invalidate datacache

- src/compute.geometry/GrasshopperDefinition.cs
- src/compute.geometry/IO/Schema.cs
* Adds Minimum and Maximum
* Replaces param type name with "Slider"
* Sets default value
> Add more information about sliders to /io

- src/compute.geometry/GrasshopperDefinition.cs
> use contextual source to define defaults, minimums, maximums

- src/compute.geometry/ResthopperEndpoints.cs
Closes #149 
I'm forcing only one thread to perform a GH solve at a time which may seem pretty heavy handed. Once we have the child process architecture in place we will still concurrent solving by using multiple processes instead of multiple threads in a single process
> Only allow one thread to perform a solve at a time

- src/compute.geometry/Program.cs
> Don't set console title when running as a windows service

- src/compute.components/LocalServer.cs
- src/compute.sln
- src/rhino.compute/ComputeChildren.cs
- src/rhino.compute/Program.cs
- src/rhino.compute/ReverseProxy.cs
- src/rhino.compute/Startup.cs
- src/rhino.compute/rhino.compute.csproj
> rename compute.rhino3d.exe to rhino.compute.exe

- src/compute.geometry/GrasshopperDefinition.cs
> Return default values for vectors and points from compute

- src/compute.geometry/Program.cs
- src/compute.geometry/Shutdown.cs
- src/compute.geometry/compute.geometry.csproj
- src/rhino.compute/ComputeChildren.cs
- src/rhino.compute/ReverseProxy.cs
- src/rhino.compute/rhino.compute.csproj
> add idle span monitoring for child processes

- src/compute.components/RemoteDefinition.cs
I had a false positive with the old method
> Use data count to check if output is a single item

- src/compute.components/LocalServer.cs
- src/compute.components/Properties/AssemblyInfo.cs
- src/compute.geometry/Bootstrapper.cs
- src/compute.geometry/Program.cs
Use the assembly info class to tell us location of installed Hops.gha
> Support Hops being memory loaded

- src/compute.components/RemoteDefinition.cs
> support paths to definitions available as URLs

- src/tests/gh_hops_lib.py
- src/tests/gh_hops_test.py
along with supporting the needed inputs/outputs
> Add pointat component for python

- src/hops/HopsComponent.cs
> Make RemoteDefinitionLocation public

- src/hops/HopsComponent.cs
> Use tree param access for hops component outputs

- src/hops/Hops.csproj
- src/hops/HopsComponent.cs
- src/hops/MemoryCache.cs
- src/hops/RemoteDefinition.cs
Context menu options for memory and server caching per component
> Add options to turn on/off memory cache per component

- src/ghhops-server-py/ghhops_server/params.py
Add
HopsBoolean, HopsBrep, HopsInteger, HopsLine, HopsMesh, HopsString, HopsSubD, HopsVector
> add more param types for python

- src/hops/HopsComponent.cs
> reassign sources when inputs change in Hops component

- src/ghhops-server-py/ghhops_server/__init__.py
- src/ghhops-server-py/ghhops_server/base.py
- src/ghhops-server-py/ghhops_server/params.py
- fixed missing log level setter
- added `default=` to input param definition options. keyword func params can only come After non-keyword ones so this limits parameters with default values to the ones at the end of func definition
> Misc fixes

- src/rhino.compute/ComputeChildren.cs
- src/rhino.compute/Program.cs
- src/rhino.compute/ReverseProxy.cs
> log max concurrent request per minute

- src/rhino.compute/ComputeChildren.cs
- src/rhino.compute/Program.cs
- src/rhino.compute/ReverseProxy.cs
- src/rhino.compute/Startup.cs
- src/rhino.compute/rhino.compute.csproj
> add command line params for rhino.compute.exe

- src/ghhops-server-py/examples/app_http.py
- src/ghhops-server-py/ghhops_server/__init__.py
- src/ghhops-server-py/ghhops_server/params.py
Closed #315 : fix spelling error for vector coerce function
Closed #316 : support list inputs and outputs
Closed #318: another form of list support
> add list support for python input and output

- src/compute.geometry/Program.cs
- src/compute.geometry/ResthopperEndpoints.cs
- src/hops/Servers.cs
- src/rhino.compute/Program.cs
- src/rhino.compute/ReverseProxy.cs
Closed #255 
rhino.compute now ships with Hops and is the process that Hops communicates with
> Include rhino.compute with Hops

- src/hops/HopsAppSettings.cs
- src/hops/HopsAppSettingsUserControl.Designer.cs
- src/hops/HopsAppSettingsUserControl.cs
- src/hops/HopsAppSettingsUserControl.resx
- src/hops/HopsComponent.cs
- src/hops/Properties/AssemblyInfo.cs
- src/hops/RemoteDefinition.cs
- src/hops/Servers.cs
- src/hops/SetDefinitionForm.cs
> Add GH preference for # children to launch at start

- src/ghhops-server-py/ghhops_server/params.py
- src/hops/HopsComponent.cs
- src/hops/RemoteDefinition.cs
> attempt to support tree input params with python

- src/hops/HopsComponent.cs
> add support for data param

- src/hops/HopsAppSettings.cs
- src/hops/HopsAppSettingsUserControl.Designer.cs
- src/hops/HopsAppSettingsUserControl.cs
- src/hops/HopsComponent.cs
- src/hops/RemoteDefinition.cs
- src/hops/SolveData.cs
- src/hops/SolveIterationQueue.cs
Less janky hops
- synchronous and asynchronous solve modes per component
- request queue for calling external processes with a max concurrent request setting
- cancellation of intermediate solves when asynchronous. If the intermediate solve request has not been made in the request queue, it is thrown away
> async solve

- src/hops/HopsAppSettings.cs
- src/hops/HopsAppSettingsUserControl.Designer.cs
- src/hops/HopsAppSettingsUserControl.cs
- src/hops/HopsComponent.cs
> save async state in gh file

- src/hops/HopsAppSettingsUserControl.cs
> Hide some preference controls on Mac

- src/hops/HopsComponent.cs
> Add option for enabled input

- src/hops/HopsComponent.cs
Add context menu item to allow setting path as a component input instead of by the context menu itself
Cite #314
> optional path input

- CHANGELOG.HOPS.md
- src/ghhops-server-py/ghhops_server/base.py
- src/hops/RemoteDefinition.cs
> rebuild component when it notices that server function has changed

- src/hops/HopsComponent.cs
> remove parallel computing and variable parameters menu items

- src/hops/HopsComponent.cs
> link help to devdocs page

- src/hops/Properties/AssemblyInfo.cs
- src/hops/RemoteDefinition.cs
> support deserialization of plane when read into Hops

- src/compute.geometry/Program.cs
See https://mcneel.myjetbrains.com/youtrack/issue/RH-63046
> Delete rhino_token env var if set at process level

- src/compute.geometry/IO/Schema.cs
- src/compute.geometry/ResthopperEndpoints.cs
- src/hops/HopsAppSettings.cs
- src/hops/HopsComponent.cs
- src/hops/Properties/AssemblyInfo.cs
- src/hops/RemoteDefinition.cs
Fixes #383 
Recursive limit of 10 defined as a GH app setting
> implement recursive calls with limits

- src/compute.geometry/GrasshopperDefinition.cs
- src/hops/RemoteDefinition.cs
> unescape strings so embedded json can be passed around

- src/compute.geometry/GrasshopperDefinition.cs
> support components as named groups

- src/hops/RemoteDefinition.cs
> Use GH_Convert to get geometry input

- src/hops/RemoteDefinition.cs
See: https://discourse.mcneel.com/t/hops-error/120525/28
Try to always deserialize output from a solve and get at error messages in case they are available. This should improve the quality of the error messages that Hops can display
> always attempt to deserialize schema in order to get at error messages

- src/compute.geometry/GrasshopperDefinition.cs
- src/hops/Properties/AssemblyInfo.cs
> have fallback when deserializing a string fails

- CHANGELOG.HOPS.md
- src/compute.geometry/GrasshopperDefinition.cs
> handle case where relays are upstream of get component

- CHANGELOG.HOPS.md
- src/hops/RemoteDefinition.cs
> resize custom icons if they are not 24x24

- CHANGELOG.HOPS.md
- src/hops/HopsComponent.cs
> export json

- src/hops/HopsComponent.cs
> removing extra separator in hops menu

- .github/workflows/workflow_ci.yml
Only uploads artifact if building from default branch.
> Workflow to build compute

- src/hops/Servers.cs
> support running with memory loading of Hops

- src/hops/HopsComponent.cs
- src/hops/Properties/launchSettings.json
- src/hops/RemoteDefinition.cs
also PathType? should stay a member variable as it is unique to each component
> path was not being set for non-filepath locations

- src/hops/Hops.csproj
Reverts mcneel/compute.rhino3d#501
> Revert "changing target platform to AnyCPU"

- src/hops/Hops.csproj
Allows hops to load in mac rhino wip
> Build hops as anycpu
